site_name: Citrix HTML5 Receiver SDK
site_description: Citrix HTML5 Receiver SDK 参考指南
theme_dir: theme_multi
markdown_extensions:
  - admonition
  - codehilite
  -  toc:
      anchorlink: true
pages:
   - 适用于 HTML5 的 HDX SDK: index.md
  - SDK 功能: capabilities.md
  - API 参考:
      - 类:
        - ReceiverError: ReceiverError.md
        - Session: session.md
      - 命名空间:
          - Receiver: citrix-receiver.md
      - 全局: global.md
  - SDK 示例: sample.md
